version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stori-flow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2prl53m7jnza"
s3_prefix = "stori-flow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
